services:
  web:
    image: fagnerfgb/caos:v2
    ports:
    - 8080:3000
    restart: always
    cpuset: "0"
    memswap_limit: 1G
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
