services:
  srv-imc:
    container_name: srv-imc
    image: fagnerfgb/imc:v1
    ports:
      - "8080:8080"
    networks:
      - srv-imc
    restart: always
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8080/health.html" ]
      timeout: 5s
      retries: 3
      start_period: 30s
networks:
  srv-imc:
    name: srv-imc-net
    driver: bridge