services:
  # Serviço Postgres
  postgre:
    # Nome do container que será criado para o serviço Postgres
    container_name: fgb-postgre
    # Imagem Docker usada para o serviço Postgres, com a tag configurada pela variável POSTGRES_TAG
    image: postgres:${POSTGRES_TAG}
    # Porta do container (5432) mapeada para a mesma porta no host
    ports:
      - 5432:5432
    # Variáveis de ambiente que configuram o banco de dados
    environment:
      # Define a senha do usuário do banco de dados
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Define o nome do usuário do banco de dados
      POSTGRES_USER: ${POSTGRES_USER}
      # Define o nome do banco de dados
      POSTGRES_DB: ${POSTGRES_DB}
    # Volume persistente para armazenar os dados do banco
    volumes:
      # Mapeia o volume postgre_docker_vol para o diretório de dados do Postgres no container
      - postgre_docker_vol:/var/lib/postgresql/data
    # Rede personalizada para isolar o serviço em um ambiente de rede específico
    networks:
      - kube_news_net    

  # Serviço da aplicação kube-news
  kube_news:
    # Imagem Docker da aplicação kube-news, com tag configurável pela variável KUBE_NEWS_TAG ou "latest" como padrão
    image: fagnerfgb/kube-news:${KUBE_NEWS_TAG:-latest}
    # Configurações para construção da imagem a partir do Dockerfile
    build:
      # Diretório onde está localizado o Dockerfile da aplicação
      context: ./src
      # Nome do arquivo Dockerfile a ser usado para construção da imagem
      dockerfile: Dockerfile
    # Nome do container que será criado para o serviço kube-news
    container_name: fgb-kube-news
    # Porta do container (8080) mapeada para a mesma porta no host
    ports:
      - 8080:8080
    # Rede personalizada para isolar o serviço em um ambiente de rede específico
    networks:
      - kube_news_net
    # Configuração para garantir que o Postgres seja iniciado antes do kube-news
    depends_on:
      - postgre
    # Variáveis de ambiente que configuram a conexão com o banco de dados
    environment:
      # Nome do banco de dados usado pela aplicação
      DB_DATABASE: ${POSTGRES_DB}
      # Nome do usuário do banco de dados usado pela aplicação
      DB_USERNAME: ${POSTGRES_USER}
      # Senha do banco de dados usada pela aplicação
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      # Nome do container do Postgres usado para conexão
      DB_HOST: fgb-postgre

# Definição do volume
volumes:
  # Configuração do volume Docker para armazenar dados do Postgres
  postgre_docker_vol:
    # Nome atribuído ao volume gerenciado pelo Docker
    name: my_postgre_vol

# Definição da rede personalizada
networks:
  # Configuração de uma rede Docker personalizada
  kube_news_net:
    # Nome atribuído à rede
    name: knews_network
    # Driver de rede utilizado para isolar os containers (bridge)
    driver: bridge