services:
  postgre:
    container_name: fgb-postgre
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    profiles:
      - dev
      - homolog
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - volume-fgb-postgre:/var/lib/postgresql/data
    networks:
      - kube_news_net    

  kube_news:
    image: fagnerfgb/kube-news:${KUBE_NEWS_TAG:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: fgb-kube-news
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    depends_on:
      - postgre
    environment:
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: fgb-postgre

volumes:
  volume-fgb-postgre:
    name: fgb-postgre-volume

networks:
  kube_news_net:
    name: knews_network
    driver: bridge