services:
  postgre:
    container_name: fgb-postgre
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - volume-fgb-postgre:/var/lib/postgresql/data
    networks:
      - kube_news_net    

  web:
    extends:
      file: ./kube-news-compose.yaml
      service: kube_news
      
volumes:
  volume-fgb-postgre:
    name: fgb-postgre-volume

networks:
  kube_news_net:
    name: knews_network
    driver: bridge