services:
  kube_news:
    image: fagnerfgb/kube-news:${KUBE_NEWS_TAG:-latest}
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: fgb-kube-news
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    depends_on:
      - postgre
    environment:
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: fgb-postgre