services:
  postgre:
    container_name: fgb-postgre
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pwdkubenews
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
      - ./volume-fgb-postgre:/var/lib/postgresql/data