FROM golang:1.22.11-alpine3.21
EXPOSE 8080
LABEL author="Fagner Geraldes Braga"
LABEL contact="fagner.fgb@gmail.com"
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
CMD [ "./main" ]